name: Pylint

on:
  workflow_dispatch:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Get newest code and run pylint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        pip install pylint
    - name: Checkout PdmVWebCore
      run: |
        git submodule init
        git submodule update
    - name: Analysing the code with pylint
      run: |
        python3 -m pylint --version
        python3 -m pylint --fail-under=9.5 --fail-on=E --reports=y `find . -type f | grep .py$ | grep -v "\./scripts/" | xargs`
